recipe detail product  customization
miamtech/mealz-documentation pull request #26
Opened 2024-06-07 12:09 UTC by ThibaultMiam

2024-06-07 12:10 UTC, ThibaultMiam commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/26?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#29** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/29?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#28** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/28?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#27** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/27?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/26?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/25?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/24?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/23?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/22?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/21?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/20?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#19** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/19?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#18** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/18?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#17** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/17?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ThibaultMiam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-10 08:07 UTC, diarmuidmcg requested changes
I would have put the components into sep files so its easy to manage

2024-06-10 08:07 UTC, diarmuidmcg commented on docs/android/features/_shared/_custom-views/recipeDetail/RecipeDetailProduct.mdx
> +### product
```suggestion
### Product
```

2024-06-10 08:07 UTC, diarmuidmcg commented on docs/android/features/_shared/_custom-views/recipeDetail/RecipeDetailProduct.mdx
> +
```suggestion
- **success** : State when data is loaded from back end
- **loading** : Still fetching data 
- **ignored** : Product will not be shown or added to basket (yet ingredient is still shown)

```

2024-06-10 08:07 UTC, diarmuidmcg commented on docs/android/features/_shared/_custom-views/recipeDetail/RecipeDetailProduct.mdx
> +To create your own recipe detail product success template you have to create class that implement `ProductSuccess`
```suggestion
#### Success

To create your own recipe detail product success template you create a class that implements `ProductSuccess`
```

2024-06-10 08:07 UTC, diarmuidmcg commented on docs/android/features/_shared/_custom-views/recipeDetail/RecipeDetailProduct.mdx
> +To create your own recipe detail product loading template you have to create class that implement `ProductLoading`
```suggestion
#### Loading

To create your own recipe detail product loading template you create a class that implements `ProductLoading`
```

2024-06-10 08:07 UTC, diarmuidmcg commented on docs/android/features/_shared/_custom-views/recipeDetail/RecipeDetailProduct.mdx
> +To create your own recipe detail product ignore template you have to create class that implement `ProductIgnore`
```suggestion
#### Ignored 

To create your own recipe detail product ignore template you create a class that implements `ProductIgnore`
```

2024-06-17 11:41 UTC, merged