Init Mealz doc
miamtech/mealz-documentation pull request #5
Opened 2024-05-24 14:43 UTC by ThibaultMiam

2024-05-24 14:44 UTC, ThibaultMiam commented
* **#5** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/5?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ThibaultMiam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-28 11:29 UTC, diarmuidmcg requested changes

2024-05-28 11:29 UTC, diarmuidmcg commented on docs/android/overview/supplierInit.md
> +IMPORTANT: passing an empty list to Mealz SDK on initialization when there are actual products in the basket will lead to unexpected side effects. If this is done, products in the user's basekt will
```suggestion
IMPORTANT: passing an empty list to Mealz SDK on initialization when there are actual products in the basket will lead to unexpected side effects. If this is done, products in the user's basket will appear as removed by the user in the Mealz basket.
```

2024-05-28 11:29 UTC, diarmuidmcg commented on docs/android/overview/supplierInit.md
> +This will update make sure both baskets are connected & up to date.
```suggestion
This will make sure both baskets are connected & up to date.
```

2024-05-28 13:57 UTC, ThibaultMiam commented
### Merge activity

* **May 28, 9:57 AM EDT**: @ThibaultMiam started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/miamtech/mealz-documentation/5).

2024-05-28 13:57 UTC, merged