Added Mealz SSR About our library
miamtech/mealz-documentation pull request #67
Opened 2024-08-06 09:07 UTC by mariePivette-mealz

Ticket: https://app.clickup.com/t/86bzvvjkk

Main change:

![image](https://github.com/user-attachments/assets/0f65ebd9-1d60-47c6-8e1a-a4aebb50651d)

2024-08-07 14:18 UTC, antonin-francois requested changes

2024-08-07 14:18 UTC, antonin-francois commented on docs/web_ssr/about/introduction.md
> +# Introduction
non par soucis de cohérence je trouve qu'il faut laisser l'intro en tout premier en dehors de la section

2024-08-08 13:41 UTC, tgrousseau approved these changes

2024-08-08 14:45 UTC, antonin-francois approved these changes

2024-08-09 09:23 UTC, merged