Added main features
miamtech/mealz-documentation pull request #74
Opened 2024-08-07 12:00 UTC by MarcDelrueMiam

https://app.clickup.com/t/86bzvvnet

2024-08-07 13:59 UTC, antonin-francois requested changes

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/pre-rendered-components.md
> +# Pre-rendered components
on avait pas dit custom elements ?

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/pre-rendered-components.md
> +```
préciser que ceux-ci sont mandatory mais que d'autres peuvent être nécessaires selon les requêtes ? arrête moi si je dis nimp

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/pre-rendered-components.md
> +To do that you'll need to **generate an authless token** and provide it to the [Authorization Header](./pre-rendered-components#http-request-headers)
```suggestion
To do that you'll need to **generate an authless token** and provide it to the [Authorization Header](./pre-rendered-components#http-request-headers).
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/pre-rendered-components.md
> +- **Authorization**: This header is required to access user information (likes, basket, suggestions). It should be formatted as `"user_id <user-token>"`. If the user is not logged in, the user token
```suggestion
- **Authorization**: This header is required to access user information (likes, basket, suggestions). It should be formatted as `"user_id <user-token>"`. If the user is not logged in, the user token must be replaced with an [authless token](./pre-rendered-components#authless-user).
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +The primary CTA on the card is the "Baskets icon" button. When clicked, Mealz' drawer opens and shows the recipes' details component. Clicking on the picture or title has the same effect.
```suggestion
The primary CTA on the card is the "Baskets icon" button. When clicked, Mealz's drawer opens and shows the recipe's details. Clicking on the picture or title has the same effect.
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +Finally, by clicking on the heart icon the user can add the recipe to Mealz' favorite recipes list. This icon only appears if the user is connected
```suggestion
Finally, by clicking on the heart icon the user can add the recipe to Mealz's favorite recipes list. This icon only appears if the user is connected.
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +> You need to have loaded the **token** to display recipes and the library needs a valid **store** to add products to cart
```suggestion
> You need to have loaded the **token** to display recipes and the library needs a valid **store** to add products to the cart
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +
```suggestion
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +  **_(Optional)_** serves parameter indicate the number of people the meal will serve.
```suggestion
  **_(Optional)_** serves parameter indicate the number of people the meal will serve
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +  **_(Optional)_** Select the orientation for the display of the card. See below for examples.
```suggestion
  **_(Optional)_** Select the orientation for the display of the card (see below for examples)
```

2024-08-07 13:59 UTC, antonin-francois commented on docs/web_ssr/main-features/recipe-card.md
> +  **_(Optional)_** Select the variant for the display of the card. Default is 1, available values are 1, 2 and 3. See below for examples.
```suggestion
  **_(Optional)_** Select the variant for the display of the card. Default is 1, available values are 1, 2 and 3 (see below for examples)
```

pour rester cohérent et éviter les . à la fin des descriptions

2024-08-08 08:02 UTC, mariePivette-mealz commented on docs/web_ssr/main-features/recipe-catalog.md
> +Recipe catalog is currently a CSR feature and will migrate into SSR shortly
```suggestion
Recipe catalog is currently a CSR feature and will migrate into SSR shortly.
```

2024-08-08 08:26 UTC, MarcDelrueMiam commented on docs/web_ssr/main-features/pre-rendered-components.md
> +```
Vu avec Thomas et non, pas de "Header spéciaux" par requête, ça sera plus des paramètres dans l'URL:

_"pour moi c'est plus simple pour les clients si
Headers = tout le temps pareil
Params = dépend des requêtes"_
Thomas - 2024

2024-08-08 08:27 UTC, MarcDelrueMiam commented on docs/web_ssr/main-features/pre-rendered-components.md
> +# Pre-rendered components
Pre-rendered custom elements 🤝 ?

2024-08-08 08:29 UTC, antonin-francois approved these changes

2024-08-08 13:39 UTC, antonin-francois requested changes

2024-08-08 13:39 UTC, antonin-francois commented on docs/web_ssr/main-features/pre-rendered-components.md
> +As previously explained, to use our pre-rendered custom components, you must retrieve them through a dedicated route, similar to how you retrieve data from a CRUD API.
```suggestion
As previously explained, to use our pre-rendered custom elements, you must retrieve them through a dedicated route, similar to how you retrieve data from a CRUD API.
```

2024-08-08 14:41 UTC, MarcDelrueMiam commented on docs/web_ssr/main-features/pre-rendered-components.md
> +- **Supplier-token**: We will provide you with your supplier token (in JWT format). This token allows us to identify you.
```suggestion
- **Supplier-token**: We will provide you with your supplier token (in Base64 format). This token allows us to identify you.
```

2024-08-08 14:44 UTC, antonin-francois approved these changes

2024-08-08 15:05 UTC, tgrousseau requested changes

2024-08-08 15:05 UTC, tgrousseau commented on docs/web_ssr/main-features/recipe-card.md
> +> On the same note, displaying a fixed recipe can be tempting if you want to have control on the content appearing on your website, but it also means that the users will always see the same recipes a
```suggestion
> Displaying a fixed recipe can be tempting if you want to have control on the content appearing on your website, but it also means that the users will always see the same recipes at the same places and may not stay interested, while our algorithm has some random elements to it that makes the content vary between sessions, giving the user more inspiration.
```
on a retiré l'Input random donc on vire le 1er paragraphe

2024-08-08 15:05 UTC, tgrousseau commented on docs/web_ssr/main-features/recipe-card.md
> +Do not forget [mandatory HTTP headers](./pre-rendered-components#http-request-headers)
```suggestion
Do not forget the [mandatory HTTP headers](./pre-rendered-components#http-request-headers)
```

2024-08-08 15:21 UTC, tgrousseau approved these changes

2024-08-09 09:23 UTC, merged