Added Mealz SSR Customization
miamtech/mealz-documentation pull request #75
Opened 2024-08-07 12:19 UTC by mariePivette-mealz

2024-08-07 13:30 UTC, antonin-francois requested changes

2024-08-07 13:30 UTC, antonin-francois commented on docs/web_ssr/customization/list-scan.md
> +Recipe catalog is currently a CSR feature
List scan not recipe catalog

2024-08-07 13:30 UTC, antonin-francois commented on docs/web_ssr/customization/internationalization.md
> +You can find those file in the Mealz SSR API project at `src/i18n/locales/**/**.json`
Je pense pas qu'ils auront accès à notre code donc pas sûr que ce soit pertinent, en revanche j'ajouterais peut-être "vous trouverez les textes remplaçables dans les description de chaque features" ou un truc du genre

2024-08-08 12:49 UTC, MarcDelrueMiam commented on docs/web_ssr/customization/internationalization.md
> +files such as fr-*your_name*.json to further tailor the content to your needs.
qsqsd

2024-08-08 12:52 UTC, MarcDelrueMiam commented on docs/web_ssr/customization/internationalization.md
> +files such as fr-*your_name*.json to further tailor the content to your needs.
```suggestion
files such as fr-*your_retail_name*.json to further tailor the content to your needs.
```

2024-08-08 15:10 UTC, tgrousseau approved these changes

2024-08-09 08:19 UTC, MarcDelrueMiam commented on docs/web_ssr/customization/affiliated-websites.md
> +5. If the user isn't logged, Mealz calls the [hookCallback](./set-up-and-usage/hooks) with params (true, false) (i.e. "*user isn't logged, but we don't care about the store for now*")
à vérifier que ce lien fonctionne une fois tout mergé

2024-08-09 08:32 UTC, MarcDelrueMiam commented on docs/web_ssr/customization/affiliated-websites.md
> +6. Once `hookCallback` has returned true, if the current POS is not the one passed in params, Mealz calls [setForcePosCallback](#set-force-pos-callback) with the id of the store selected by the user
```suggestion
6. Once `hookCallback` has returned true, if the current POS is not the one passed in params, Mealz calls forcePosCallback method (defined via [setForcePosCallback](#set-force-pos-callback)) with the id of the store selected by the user on the affiliated website in param
```

2024-08-09 08:32 UTC, MarcDelrueMiam commented on docs/web_ssr/customization/affiliated-websites.md
> +7. Once `setForcePosCallback` has returned true, Mealz adds all products that were added to the basket on the affiliated website to your cart, as if the user had added them all at the same time on yo
```suggestion
7. Once `forcePosCallback` has returned true, Mealz adds all products that were added to the basket on the affiliated website to your cart, as if the user had added them all at the same time on your website
```

2024-08-09 08:45 UTC, MarcDelrueMiam approved these changes

2024-08-09 09:13 UTC, antonin-francois approved these changes

2024-08-09 09:20 UTC, merged