Added Mealz SSR Styling
miamtech/mealz-documentation pull request #76
Opened 2024-08-07 12:55 UTC by mariePivette-mealz

2024-08-07 13:17 UTC, antonin-francois requested changes

2024-08-07 13:17 UTC, antonin-francois commented on docs/web_ssr/styling.md
> +    --miam-border-radius: 3px;
peut-être mettre des variables --miam-ds à la place du coup ?

2024-08-07 14:19 UTC, antonin-francois requested changes

2024-08-07 14:19 UTC, antonin-francois commented on docs/web_ssr/styling.md
>      --miam-border-radius: 3px;
```suggestion
```

ça existe pu

2024-08-08 15:16 UTC, tgrousseau requested changes

2024-08-08 15:16 UTC, tgrousseau commented on docs/web_ssr/styling.md
> +    }
Le font-weight est lié aux classes .weight-XXX (ex: `.miam-ds-text.weight-xl`) du coup c'est pas l'exemple le + pertinent
```suggestion
    .miam-ds-text {
      font-family: "Roboto";
    }
```
À ce sujet, dans une prochaine itération de la doc ça pourrait être bien de documenter un peu plus en profondeur miam-ds (avec des sections pour les boutons, les textes, les tabs etc, un peu dans le style de la démo de miam-ds ou dans le style des maquettes)

2024-08-08 15:16 UTC, tgrousseau commented on docs/web_ssr/styling.md
> +> The only thing you need to keep in mind is that your override must be read by the DOM **after** our CSS so it overrides correctly.
```suggestion
> The only thing you need to keep in mind is that your override must either be read by the DOM **after** our CSS or have more precision to override it correctly.
```

2024-08-08 15:23 UTC, tgrousseau approved these changes

2024-08-08 15:26 UTC, antonin-francois approved these changes

2024-08-09 09:15 UTC, merged