reorganize recipe card customization doc
miamtech/mealz-documentation pull request #77
Opened 2024-08-07 14:19 UTC by ThibaultMiam

2024-08-07 14:19 UTC, ThibaultMiam commented
* **#77** <a href="https://app.graphite.dev/github/pr/miamtech/mealz-documentation/77?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ThibaultMiam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-07 14:30 UTC, antonin-francois requested changes

2024-08-07 14:30 UTC, antonin-francois commented on docs/android/features/recipe-card/customize-view/RecipeCard-customization.mdx
> +RecipeCard is one of the most use components, it has three customization states: **success**, **loading** & **empty**
```suggestion
RecipeCard is one of the most used components, it has three customization states: **success**, **loading** & **empty**
```

2024-08-07 14:30 UTC, antonin-francois commented on docs/android/features/recipe-card/customize-view/RecipeCard-customization.mdx
> +Recipe card success is one of those three states, it's visible when all data has been fetched without any error.
```suggestion
Recipe card success is one of those three states, it's visible when all of the data has been fetched without any error. 
```

2024-08-07 14:30 UTC, antonin-francois commented on docs/android/features/recipe-card/customize-view/RecipeCard-customization.mdx
> +To create your own recipe card success template you create a class that implements `RecipeCardSuccess`
```suggestion
To create your own recipe card success template you create a class that implements `RecipeCardSuccess`.
```

2024-08-07 14:30 UTC, antonin-francois commented on docs/android/features/recipe-card/customize-view/RecipeCard-customization.mdx
> +View temmplate is **Deprecated** you must use **catalog** and **shelf** instead
```suggestion
View template is **Deprecated** you must use **catalog** and **shelf** instead
```

2024-08-07 14:30 UTC, antonin-francois commented on docs/android/features/recipe-card/customize-view/RecipeCard-customization.mdx
> +As for Success state basic Laoding view has been **deprecated** you must use catalog and shelf loading.
```suggestion
As for the Success state, the basic Loading view has been **deprecated** you must use catalog and shelf loading.
```

2024-08-07 14:30 UTC, antonin-francois commented on docs/android/features/recipe-card/customize-view/RecipeCard-customization.mdx
> +You can choose to have to differents design for the recipe card in our catalog and in your shelf.
```suggestion
You can choose to have to different designs for the recipe card in our catalog and in your shelf.
```

2024-08-08 13:38 UTC, antonin-francois approved these changes

2024-08-22 12:28 UTC, diarmuidmcg approved these changes

2024-08-23 08:04 UTC, antonin-francois requested changes
c'est 4.0 ou 4.1 ou les deux ?

2024-08-23 08:40 UTC, antonin-francois approved these changes

2024-08-23 09:09 UTC, diarmuidmcg approved these changes

2024-08-23 09:10 UTC, merged