Catalog doc
miamtech/mealz-documentation pull request #95
Opened 2024-09-09 07:51 UTC by ThibaultMiam

2024-09-13 10:15 UTC, diarmuidmcg requested changes

2024-09-13 10:15 UTC, diarmuidmcg commented on docs/android/features/catalog/customize-view/toolbar.mdx
> +This template allow you to customize Categories ligne in home page of the catalog
```suggestion
This template allows you to customize the toolbar at the top of the catalog page.
```

2024-09-13 10:15 UTC, diarmuidmcg commented on docs/android/features/catalog/how-to-use.mdx
> +including direct link to recipe collection.
```suggestion
As we said on the previous page, there are two ways to use the catalog :

    - Basic implementation : an all-in-one component that embeds the navigation and all needed other components
    - Custom implementation : were you can handle navigation by yourself and link components that you need

## Basic implementation 

For this implementation you will need CatalogJourney component, it's an all-in-one component merging all the available features of the catalog.
It includes a direct link to recipe collections. 
```

2024-09-13 10:15 UTC, diarmuidmcg commented on docs/android/features/catalog/walkthrough.md
> +
```suggestion
There are two diffrent ways to add this component to your project : 
    - basic implementation : an all-inone component that embed navigation and all needed other components
    - custom implementation : were you can handle navigation by yourself and link components that you need 

```

2024-09-17 07:53 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/category.mdx
> +This template allow you to customize Categories ligne in home page of the catalog
ok

2024-09-17 07:54 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/category.mdx
> +class MyCustomICatalogCategoriesPageCategory: CatalogCategoriesPageCategory {
ok

2024-09-17 07:54 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/category.mdx
> +    val goToCategoryPage: (category: Package) -> Unit // to before navigation
ok

2024-09-17 07:55 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/floating.mdx
> +This template allow you to put an overlay that will be present on main page.
ok

2024-09-17 07:55 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/floating.mdx
> +by defautl it's set to `Alignment.BottomEnd`.
ok

2024-09-17 08:00 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/search.mdx
> +    val onApply: (String) -> Unit // to call before navigate to result page
ok

2024-09-17 08:00 UTC, ThibaultMiam commented on docs/android/features/catalog/customize-view/toolbar.mdx
> +This template allow you to customize Categories ligne in home page of the catalog
ok

2024-09-17 08:05 UTC, ThibaultMiam commented on docs/android/features/catalog/how-to-use.mdx
> +including direct link to recipe collection.
ok

2024-09-27 15:28 UTC, merged